name: Swift (Microsoft Windows)

on: [push]

jobs:
  build:
    name: Swift 6.1 on ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: compnerd/gha-setup-swift@v0.3.0
        with:
          branch: swift-6.1-release
          tag: 6.1-RELEASE
      - uses: actions/checkout@v4
      - name: ğŸ™ Fetch Git Submodules
        run: git submodule update --init --recursive
      - name: ğŸ“¦ Build
        run: swift build -c release
